Modernize CI and make 3.10 min python

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -40,8 +40,8 @@ jobs:
         python-version: '3.14'
     - name: Install dependencies
       run: |-
-        python -m pip install pip -U
-        python -m pip install flake8
+        python -m pip install pip uv -U
+        python -m uv pip install flake8
     - name: Lint with flake8
       run: |-
         # stop the build if there are Python syntax errors or undefined names
@@ -67,14 +67,14 @@ jobs:
         python-version: '3.14'
     - name: Upgrade pip
       run: |-
-        python -m pip install pip -U
+        python -m pip install pip uv -U
         python -m pip install --prefer-binary -r requirements/tests.txt
         python -m pip install --prefer-binary -r requirements/runtime.txt
     - name: Build sdist
       shell: bash
       run: |-
-        python -m pip install pip -U
-        python -m pip install setuptools>=77 wheel build twine
+        python -m pip install pip uv -U
+        python -m uv pip install setuptools>=77 wheel build twine
         python -m build --sdist --outdir wheelhouse
         python -m twine check ./wheelhouse/timerit*.tar.gz
     - name: Install sdist
@@ -145,8 +145,8 @@ jobs:
     - name: Build pure wheel
       shell: bash
       run: |-
-        python -m pip install pip -U
-        python -m pip install setuptools>=77 wheel build twine
+        python -m pip install pip uv -U
+        python -m uv pip install setuptools>=77 wheel build twine
         python -m build --wheel --outdir wheelhouse
         python -m twine check ./wheelhouse/timerit*.whl
     - name: Show built files
@@ -172,127 +172,105 @@ jobs:
         # Xcookie generates an explicit list of environments that will be used
         # for testing instead of using the more concise matrix notation.
         include:
-        - python-version: '3.6'
-          install-extras: ''
-          os: ubuntu-20.04
-          arch: auto
-          allow-prereleases: 'false'
-          check-latest: 'false'
-          use-lockfile: 'false'
-        - python-version: '3.6'
-          install-extras: ''
-          os: macos-13
-          arch: auto
-          allow-prereleases: 'false'
-          check-latest: 'false'
-          use-lockfile: 'false'
-        - python-version: '3.6'
-          install-extras: ''
-          os: windows-latest
-          arch: auto
-          allow-prereleases: 'false'
-          check-latest: 'false'
-          use-lockfile: 'false'
-        - python-version: '3.14'
-          install-extras: ''
+        - python-version: '3.10'
+          install-extras: tests
           os: ubuntu-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
-          use-lockfile: 'false'
+          use-lockfile: 'true'
+          lock-requirements: requirements/locks/tests.txt
+        - python-version: '3.10'
+          install-extras: tests
+          os: macOS-latest
+          arch: auto
+          allow-prereleases: 'false'
+          check-latest: 'false'
+          use-lockfile: 'true'
+          lock-requirements: requirements/locks/tests.txt
+        - python-version: '3.10'
+          install-extras: tests
+          os: windows-latest
+          arch: auto
+          allow-prereleases: 'false'
+          check-latest: 'false'
+          use-lockfile: 'true'
+          lock-requirements: requirements/locks/tests.txt
         - python-version: '3.14'
-          install-extras: ''
+          install-extras: tests,optional
+          os: ubuntu-latest
+          arch: auto
+          allow-prereleases: 'false'
+          check-latest: 'false'
+          use-lockfile: 'true'
+          lock-requirements: requirements/locks/tests-optional.txt
+        - python-version: '3.14'
+          install-extras: tests,optional
+          os: macOS-latest
+          arch: auto
+          allow-prereleases: 'false'
+          check-latest: 'false'
+          use-lockfile: 'true'
+          lock-requirements: requirements/locks/tests-optional.txt
+        - python-version: '3.14'
+          install-extras: tests,optional
+          os: windows-latest
+          arch: auto
+          allow-prereleases: 'false'
+          check-latest: 'false'
+          use-lockfile: 'true'
+          lock-requirements: requirements/locks/tests-optional.txt
+        - python-version: '3.14'
+          install-extras: tests
           os: macOS-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
         - python-version: '3.14'
-          install-extras: ''
+          install-extras: tests
           os: windows-latest
-          arch: auto
-          allow-prereleases: 'false'
-          check-latest: 'false'
-          use-lockfile: 'false'
-        - python-version: '3.14'
-          install-extras: ''
-          os: macOS-latest
-          arch: auto
-          allow-prereleases: 'false'
-          check-latest: 'false'
-          use-lockfile: 'false'
-        - python-version: '3.14'
-          install-extras: ''
-          os: windows-latest
-          arch: auto
-          allow-prereleases: 'false'
-          check-latest: 'false'
-          use-lockfile: 'false'
-        - python-version: '3.6'
-          install-extras: ''
-          os: ubuntu-20.04
-          arch: auto
-          allow-prereleases: 'false'
-          check-latest: 'false'
-          use-lockfile: 'false'
-        - python-version: '3.7'
-          install-extras: ''
-          os: ubuntu-22.04
-          arch: auto
-          allow-prereleases: 'false'
-          check-latest: 'false'
-          use-lockfile: 'false'
-        - python-version: '3.8'
-          install-extras: ''
-          os: ubuntu-latest
-          arch: auto
-          allow-prereleases: 'false'
-          check-latest: 'false'
-          use-lockfile: 'false'
-        - python-version: '3.9'
-          install-extras: ''
-          os: ubuntu-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
         - python-version: '3.10'
-          install-extras: ''
+          install-extras: tests,optional
           os: ubuntu-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
         - python-version: '3.11'
-          install-extras: ''
+          install-extras: tests,optional
           os: ubuntu-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
         - python-version: '3.12'
-          install-extras: ''
+          install-extras: tests,optional
           os: ubuntu-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
         - python-version: '3.13'
-          install-extras: ''
+          install-extras: tests,optional
           os: ubuntu-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
         - python-version: '3.14'
-          install-extras: ''
+          install-extras: tests,optional
           os: ubuntu-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
         - python-version: '3.15'
-          install-extras: ''
+          install-extras: tests,optional
           os: ubuntu-latest
           arch: auto
           allow-prereleases: 'true'
@@ -300,77 +278,49 @@ jobs:
           experimental: true
           use-lockfile: 'false'
         - python-version: pypy-3.11
-          install-extras: ''
+          install-extras: tests,optional
           os: ubuntu-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
-        - python-version: '3.6'
-          install-extras: ''
-          os: macos-13
-          arch: auto
-          allow-prereleases: 'false'
-          check-latest: 'false'
-          use-lockfile: 'false'
-        - python-version: '3.7'
-          install-extras: ''
-          os: macos-13
-          arch: auto
-          allow-prereleases: 'false'
-          check-latest: 'false'
-          use-lockfile: 'false'
-        - python-version: '3.8'
-          install-extras: ''
-          os: macOS-latest
-          arch: auto
-          allow-prereleases: 'false'
-          check-latest: 'false'
-          use-lockfile: 'false'
-        - python-version: '3.9'
-          install-extras: ''
-          os: macOS-latest
-          arch: auto
-          allow-prereleases: 'false'
-          check-latest: 'false'
-          use-lockfile: 'false'
         - python-version: '3.10'
-          install-extras: ''
+          install-extras: tests,optional
           os: macOS-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
         - python-version: '3.11'
-          install-extras: ''
+          install-extras: tests,optional
           os: macOS-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
         - python-version: '3.12'
-          install-extras: ''
+          install-extras: tests,optional
           os: macOS-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
         - python-version: '3.13'
-          install-extras: ''
+          install-extras: tests,optional
           os: macOS-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
         - python-version: '3.14'
-          install-extras: ''
+          install-extras: tests,optional
           os: macOS-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
         - python-version: '3.15'
-          install-extras: ''
+          install-extras: tests,optional
           os: macOS-latest
           arch: auto
           allow-prereleases: 'true'
@@ -378,77 +328,49 @@ jobs:
           experimental: true
           use-lockfile: 'false'
         - python-version: pypy-3.11
-          install-extras: ''
+          install-extras: tests,optional
           os: macOS-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
-        - python-version: '3.6'
-          install-extras: ''
-          os: windows-latest
-          arch: auto
-          allow-prereleases: 'false'
-          check-latest: 'false'
-          use-lockfile: 'false'
-        - python-version: '3.7'
-          install-extras: ''
-          os: windows-latest
-          arch: auto
-          allow-prereleases: 'false'
-          check-latest: 'false'
-          use-lockfile: 'false'
-        - python-version: '3.8'
-          install-extras: ''
-          os: windows-latest
-          arch: auto
-          allow-prereleases: 'false'
-          check-latest: 'false'
-          use-lockfile: 'false'
-        - python-version: '3.9'
-          install-extras: ''
-          os: windows-latest
-          arch: auto
-          allow-prereleases: 'false'
-          check-latest: 'false'
-          use-lockfile: 'false'
         - python-version: '3.10'
-          install-extras: ''
+          install-extras: tests,optional
           os: windows-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
         - python-version: '3.11'
-          install-extras: ''
+          install-extras: tests,optional
           os: windows-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
         - python-version: '3.12'
-          install-extras: ''
+          install-extras: tests,optional
           os: windows-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
         - python-version: '3.13'
-          install-extras: ''
+          install-extras: tests,optional
           os: windows-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
         - python-version: '3.14'
-          install-extras: ''
+          install-extras: tests,optional
           os: windows-latest
           arch: auto
           allow-prereleases: 'false'
           check-latest: 'false'
           use-lockfile: 'false'
         - python-version: '3.15'
-          install-extras: ''
+          install-extras: tests,optional
           os: windows-latest
           arch: auto
           allow-prereleases: 'true'
@@ -456,7 +378,7 @@ jobs:
           experimental: true
           use-lockfile: 'false'
         - python-version: pypy-3.11
-          install-extras: ''
+          install-extras: tests,optional
           os: windows-latest
           arch: auto
           allow-prereleases: 'false'
@@ -494,6 +416,8 @@ jobs:
       shell: bash
       env:
         INSTALL_EXTRAS: ${{ matrix.install-extras }}
+        USE_UV_LOCK: ${{ matrix.use-lockfile }}
+        LOCK_REQUIREMENTS: ${{ matrix.lock-requirements }}
       run: |-
         if [[ "${RUNNER_OS:-}" == "Windows" ]]; then
             MSVC_CL_EXE="$(command -v cl.exe || true)"
@@ -510,11 +434,11 @@ jobs:
         echo "Finding the path to the wheel"
         ls wheelhouse || echo "wheelhouse does not exist"
         echo "Installing helpers: update pip"
-        python -m pip install pip -U
+        python -m pip install pip uv -U
         echo "Installing helpers: setuptools"
-        python -m pip install setuptools>=77 setuptools_scm wheel build -U
+        python -m uv pip install --resolution=highest setuptools>=77 setuptools_scm wheel build -U
         echo "Installing helpers: tomli and pkginfo"
-        python -m pip install tomli pkginfo packaging
+        python -m uv pip install --resolution=highest tomli pkginfo packaging
         export WHEEL_FPATH=$(python -c "if 1:
             import pathlib
             from packaging import tags
@@ -549,7 +473,21 @@ jobs:
             INSTALL_TARGET="${WHEEL_FPATH}"
         fi
         echo "INSTALL_TARGET=$INSTALL_TARGET"
-        python -m pip install --prefer-binary "${INSTALL_TARGET}"
+        LOCK_ARGS=()
+        if [[ "${USE_UV_LOCK:-false}" == "true" ]]; then
+            if [[ -z "${LOCK_REQUIREMENTS:-}" ]]; then
+                echo "USE_UV_LOCK=true but LOCK_REQUIREMENTS is empty"
+                exit 1
+            fi
+            if [[ ! -f "$LOCK_REQUIREMENTS" ]]; then
+                echo "Missing checked-in lock requirements: $LOCK_REQUIREMENTS"
+                exit 1
+            fi
+            echo "Using checked-in lock requirements: $LOCK_REQUIREMENTS"
+            cat "$LOCK_REQUIREMENTS"
+            LOCK_ARGS=(--constraint "$LOCK_REQUIREMENTS")
+        fi
+        python -m uv pip install --prerelease=allow "${LOCK_ARGS[@]}" "${INSTALL_TARGET}"
         echo "Install finished."
     - name: Test wheel ${{ matrix.install-extras }}
       id: test_wheel
